// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using samPharma.Data;

#nullable disable

namespace samPharma.Migrations
{
    [DbContext(typeof(samDbContext))]
    [Migration("20221001131616_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("samPharma.Models.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Customer_Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer_Contact")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer_ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer_Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Customer_Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("samPharma.Models.ExpiryDate", b =>
                {
                    b.Property<long>("Expiry_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Batch_Number")
                        .HasColumnType("longtext");

                    b.Property<long>("Drug_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Expiry_Date")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Manufacture_Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Expiry_Id");

                    b.ToTable("expirydate");
                });

            modelBuilder.Entity("samPharma.Models.Order", b =>
                {
                    b.Property<long>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount_Added")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Customer_Reference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Drug_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Order_Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Payment_Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Order_Id");

                    b.ToTable("order");
                });

            modelBuilder.Entity("samPharma.Models.Product", b =>
                {
                    b.Property<long>("Drug_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Drug_Dosage")
                        .HasColumnType("datetime");

                    b.Property<string>("Drug_ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Drug_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Drug_Type")
                        .HasColumnType("longtext");

                    b.HasKey("Drug_Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("samPharma.Models.Stock", b =>
                {
                    b.Property<long>("Drug_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Buy_Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Current_Invent")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Selling_Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Supplier_Id")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Supply_Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Drug_Id");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("samPharma.Models.Supplier", b =>
                {
                    b.Property<long>("Expiry_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Supplier_Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier_Contact")
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier_Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("Expiry_ID");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("samPharma.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("StaffId")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
